Repository DiamondLightSource/graph-federation, pull requests merged in 2024-07, with the labels that each got.

#26 Python service how-to guide
  docs/how-tos/python_service.md
  mkdocs.yaml
Labels: documentation

#20 add CI to compose supergraph schema and publish to OCI
  .github/workflows/schema-compose.yaml
  charts/supergraph/Chart.yaml
  charts/supergraph/template/schema-configmap.yaml
Labels: enhancement

#28 Enable homepage on nightly router
  charts/apps/Chart.yaml
  charts/apps/templates/nightly.yaml
Labels: enhancement, helm

#34 Use mounted supergraph file to provide schema
  charts/graph/Chart.yaml
  charts/graph/values.yaml
Labels: enhancement, helm

#30 add docs on how to consume graphql with python
  docs/how-tos/python_consume.md
Labels: documentation

#29 add docs on how to provide data through a graphql service in rust
  docs/how-tos/rust_service.md
Labels: documentation

#35 Remove apikey
  charts/graph/Chart.yaml
  charts/graph/templates/graph-apikey-secret.yaml
Labels: helm
