Repository DiamondLightSource/graph-federation, pull requests merged in 2024-10, with the labels that each got.

#48 Add how-to guide describing subgraph schema addition
  docs/how-tos/add-subgraph-schema.md
Labels: documentation

#49 add how-to guide for typescript graphql consumer
  docs/how-tos/typescript_consume.md
Labels: documentation

#50 Only create commit if a schema diff exists
  docs/how-tos/add-subgraph-schema.md
Labels: documentation

#62 Disable oauth2 proxy provider button screen
  charts/graph/Chart.yaml
  charts/graph/values.yaml
Labels: enhancement, helm

#63 Refactor CI to use central flow definition
  .github/workflows/_compose_workflow.yaml
  .github/workflows/_docs.yaml
  .github/workflows/_helm_lint.yaml
  .github/workflows/_supergraph_generate.yaml
  .github/workflows/_supergraph_publish.yaml
  .github/workflows/_update_workflow.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema-compose.yaml
  .github/workflows/schema_comparison.yaml
Labels: github actions
